### ISSUE TITLE
Appends a blank page at the end of PDF file

### ISSUE THREAD

**Issue by 6vedant** [brospars/mkdocs-page-pdf#9]
I noticed that for every PDF file created, I see a blank page unnecessarily added at the end of file. Can we remove it?

**Comment by brospars** [comment]
Could you share an example to reproduce ?

**Comment by 6vedant** [comment]
[wearableOEM-rm-915-2k (2).pdf](https://github.com/brospars/mkdocs-page-pdf/files/10570227/wearableOEM-rm-915-2k.2.pdf)
[index (2).pdf](https://github.com/brospars/mkdocs-page-pdf/files/10570229/index.2.pdf)

check these two PDF files, i am getting a blank page appended as the last page.

**Comment by 6vedant** [comment]
This is my yml file.
```yml
# Author: Aaron Do
# Date: 13 Dec 2022
# Note that not all options are supported by all themes
site_name: Doodle Labs Technical Library
site_url: http://127.0.0.1:8000
nav:
    - Home: index.md
    - 'Application Notes': 
        - 'Antenna Recommendations for UAS': app-notes/ant-recommendations.md
        - 'VOXL Integration Guide': app-notes/voxl-int-guide.md
        - 'Skynode Integration Guide': app-notes/skynode.md
        - 'Low Latency C&C and Video Streaming with the Nvidia Jetson Nano': app-notes/video-urllc-jetsonNano.md
        - 'Integration of Smart Radio with QGroundControl and the Flight Controller': app-notes/qgc-pixhawk.md
        - 'GCS Reference Design': app-notes/gcs-ref.md
        - 'Wearable Smart Radio Testing Results': app-notes/wearable-eval.md 
        - 'Optimizing the RF Link': radio-tech/optimizing-the-rf-link.md
        - 'Supported Networking Modes': radio-tech/sr-networking.md
        - 'Throughput Estimation': radio-tech/throughput.md
    - 'Hardware Guides': 
        - 'Hardware Integration Guidelines': hw-guides/hw-integration-guidelines.md
        - 'Hardware Interfaces': hw-guides/hw-interfaces.md
        - 'Pin Diagrams': 
            - 'nano-OEM': hw-guides/pin-diagrams/nanooem.md
            - 'mini-OEM': hw-guides/pin-diagrams/minioem.md
            - 'nano/mini-OEM Eval Kit': hw-guides/pin-diagrams/minioem-evk.md
            - 'Wearable': hw-guides/pin-diagrams/wearable.md
            - 'Wearable Eval Kit': hw-guides/pin-diagrams/wearable-evk.md
            - 'Embedded': hw-guides/pin-diagrams/embedded.md
            - 'External Radio and Embedded EVK': hw-guides/pin-diagrams/external.md
    - 'Software Guides':
        - 'Getting Started': sw-guides/getting-started.md
        - 'General Configuration': sw-guides/general-config.md
        - 'Model-Specific Configuration': sw-guides/model-specific.md
        - 'Command-Line Interface': sw-guides/cli.md
        - 'Remote Management Guide': sw-guides/remote-config-guide.md
        - 'Central Configuration, ACS, and Link Recovery': sw-guides/central-config.md
        - 'Serial Interface Guide': sw-guides/serial-guide.md
        - 'GPIO usage and LED Blinking': sw-guides/gpio-led-blinking.md
        - 'Remote ID Integration Guide': sw-guides/rid-guide.md
        - 'Spectrum Scanning': sw-guides/spectrum-scanner.md
    - 'Datasheets':
        - 'Smart Radio':
#            - 'Datasheets Overview': datasheets/overview.md
            - 'License Free Radios':
#                - 'Multi-Band 900 + WiFi Bands':  
                - '902 - 928 MHz':  
                    - 'Wearable': datasheets/wearableOEM/wearableOEM-rm-915-2k.md
                    - 'Embedded': datasheets/Emb-ext/emb-rm-915-2j.md
                    - 'External': datasheets/Emb-ext/emb-ext-rm-915-2j.md
                - '2400 - 2482 MHz (Wi-Fi)':
                    - 'mini-OEM': datasheets/miniOEM/miniOEM-rm-2450-2l.md
                    - 'nano-OEM': datasheets/miniOEM/miniOEM-rm-2450-2l.md
                    - 'Wearable': datasheets/wearableOEM/wearableOEM-rm-2450-2k.md
                    - 'Embedded': datasheets/Emb-ext/emb-ext-rm-2450-2j.md
                    - 'External': datasheets/Emb-ext/emb-ext-rm-2450-2j.md
                - '3550 - 3700 MHz (CBRS)': 
                    - 'Embedded and External': datasheets/Emb-ext/emb-ext-rm-3625-2j.md
                - '5150 - 5875 MHz (Wi-Fi)': 
                    - 'Wearable and OEM': datasheets/wearableOEM/wearableOEM-rm-5500-2k.md
                - '5725 - 5875 MHz': 
                    - 'Embedded and External': datasheets/Emb-ext/emb-ext-rm-5800-2j.md
            - 'Special Band Radios(Helix Family)': 
                - 'Multi-Band 1350 - 2510 MHz (L, M2-M6)':
                    - 'mini-OEM': datasheets/miniOEM/miniOEM-rm-2025-2l.md
                    - 'nano-OEM': datasheets/nanoOEM/nanoOEM-rm-2025-1l.md
                - 'Multi-Band 1625 - 2510 MHz (M1-M6)':
                    - 'mini-OEM': datasheets/miniOEM/miniOEM-rm-2025-2l.md
                    - 'nano-OEM': datasheets/nanoOEM/nanoOEM-rm-2025-1l.md
                - '1350 - 1390 MHz (L-band)': 
                    - 'Embedded and External': datasheets/Emb-ext/emb-ext-rm-1370-2j.md
                - '2200 - 2300 MHz':
                    - 'Embedded and External': datasheets/Emb-ext/emb-ext-rm-2250-2j.md
                - 'Multi-Band 4400 - 5875 MHz (C-Band) (preliminary)': 
                    - 'Wearable and OEM V2': datasheets/palix/palix-cband.md
                - 'Japan Robotics 5650 - 5755 MHz':
                    - 'mini-OEM': datasheets/wearableOEM/wearableOEM-rm-5700-2k.md
            # - 'Nano OEM':
            #     - 'Nano OEM RM-2025-1L': datasheets/nanoOEM/nanoOEM-rm-2025-1l.md
            # - 'Mini OEM':
            #     - '1625 - 2510 MHz (M1-M6) Helix': datasheets/miniOEM/miniOEM-rm-2025-2l.md
            #     - '2400 - 2482 MHz (Wi-Fi)': datasheets/miniOEM/miniOEM-rm-2450-2l.md
            # - 'Wearable and OEM':
            #     - '2400 - 2482 MHz (Wi-Fi)': datasheets/wearableOEM/wearableOEM-rm-2450-2k.md
            #     - '902 - 928 MHz (ISM)': datasheets/wearableOEM/wearableOEM-rm-915-2k.md
            #     - '5150 - 5875 MHz (Wi-Fi)': datasheets/wearableOEM/wearableOEM-rm-5500-2k.md
            #     - '5650 - 5755 MHz (Japan Robotics)': datasheets/wearableOEM/wearableOEM-rm-5700-2k.md
            # - 'Embedded and External':
            #     - '902 - 928 MHz': datasheets/Emb-ext/emb-ext-rm-915-2j.md
            #     - '1350 - 1390 MHz (L-band)': datasheets/Emb-ext/emb-ext-rm-1370-2j.md
            #     - '2200 - 2300 MHz (S-band)': datasheets/Emb-ext/emb-ext-rm-2250-2j.md
            #     - '2400 - 2482 MHz (Wi-Fi)': datasheets/Emb-ext/emb-ext-rm-2450-2j.md
            #     - '3550 - 3700 MHz (CBRS)': datasheets/Emb-ext/emb-ext-rm-3625-2j.md
            #     - '5725 - 5875 MHz': datasheets/Emb-ext/emb-ext-rm-5800-2j.md
        - 'Industrial Wi-Fi':
            - 'Wi-Fi 4 (11n)': datasheets/wifi-transceivers/comingsoon.md
            - 'Wi-Fi 5 (11ac)': datasheets/wifi-transceivers/comingsoon.md
            - 'Wi-Fi 6 (11ax)': datasheets/wifi-transceivers/comingsoon.md
#        - 'Wearable and OEM V2':
#            - '4400 - 5875 MHz (C-Band) (preliminary)': datasheets/palix/palix-cband.md
    - 'Troubleshooting':
        - 'Backup Reset and Upgrade': troubleshooting/backup-upgrade.md
        - 'Radio Access issues': troubleshooting/radio-access.md
        - 'Link Quality issues': troubleshooting/link-quality.md
        - 'UART and USB issues': troubleshooting/uart-usb.md
        - 'Crashes, Reboots etc': troubleshooting/crashes-reboots.md
theme: 
    name: material # mkdocs, readthedocs, material...
    logo: img/logo.png
    favicon: img/favicon.png
    palette:
        primary: orange
        accent: purple
        scheme: default
    features: 
        - navigation.tabs  
        - navigation.top  
        - navigation.tabs.sticky
        - toc.follow    
    navigation_depth: 3 # for mkdocs theme
markdown_extensions: # for material theme    
    - admonition
    - attr_list
    - md_in_html
    - toc:
        toc_depth: 3
extra_css: [extra.css]
plugins:
    - search
    - page-to-pdf
```

**Comment by brospars** [comment]
This is a recent chrome bug : 
- https://stackoverflow.com/questions/74698700/after-the-new-version-of-chrome108-it-adds-an-extra-blank-page-when-printing
- https://support.google.com/chrome/thread/191619088?hl=en&msgid=192661374

You can simply add the following to you `extra.css` : 
```css
body {
    contain: strict;
}
```

**Comment by drawlings** [comment]
I recommend `contain: content` instead of `contain: strict`, or else it will cut off everything but the first page, even if there is actual content there. This is what I put in `extra.css` to fix this issue:

```css
@media print {
    body { contain: content; }
}
```
